---
name: Sync Folders

"on":
  push:
    branches:
      - main
    paths:
      - 'docs/docs/**'
      - 'docs/sidebars.ts'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v5
        with:
          path: source-repo

      - name: Checkout target repository
        uses: actions/checkout@v5
        with:
          repository: opsmill/infrahub-docs
          token: ${{ secrets.PAT_TOKEN }}
          path: target-repo

      - name: Sync folders
        run: |
          rm -rf target-repo/docs/docs-{{PROJECT_NAME}}/*
          rm -f target-repo/docs/sidebars-{{PROJECT_NAME}}.ts
          cp -r source-repo/docs/docs/* target-repo/docs/docs-{{PROJECT_NAME}}/
          cp source-repo/docs/sidebars.ts target-repo/docs/sidebars-{{PROJECT_NAME}}.ts
          cd target-repo
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git diff --quiet && git diff --staged --quiet || \
            git commit -m "Sync docs from {{PROJECT_NAME}} repo" && git push
